# SELECT ID, FISH_NAME, LENGTH
#   FROM (SELECT MAX(A.LENGTH), A.ID, A.LENGTH, B.FISH_NAME
#           FROM FISH_INFO A, FISH_NAME_INFO B
#          WHERE A.FISH_TYPE = B.FISH_TYPE
#          GROUP BY A.FISH_TYPE)

# SELECT A.ID AS ID, B.FISH_NAME, A.LENGTH
#   FROM FISH_INFO A, FISH_NAME_INFO B
#  WHERE A.FISH_TYPE = B.FISH_TYPE
  

# SELECT MAX(LENGTH), FISH_TYPE, ID, LENGTH
#           FROM FISH_INFO
#          GROUP BY FISH_TYPE, ID, LENGTH
         
SELECT ID, FISH_NAME, LENGTH
  FROM (SELECT A.*, 
               B.FISH_NAME,
               ROW_NUMBER() OVER (PARTITION BY A.FISH_TYPE ORDER BY A.LENGTH DESC) AS RN
          FROM FISH_INFO A, 
               FISH_NAME_INFO B
         WHERE A.FISH_TYPE = B.FISH_TYPE) RANKED
 WHERE RN = 1
 ORDER BY ID;

         
# WHERE A.FISH_TYPE = B.FISH_TYPE